/* Shared translations; external websites and user-authored book text are never translated. */
(function () {
const en={
'上班摸鱼神器':'Office Escape','上班摸鱼神器 · 透明阅读工具':'Office Escape · Transparent Reader','轻屿':'Office Escape','给日常留一点空白':'A little room for yourself',
'⠿ 拖动':'⠿ Drag','⚙ 设置':'⚙ Settings','展开':'Expand','隐藏':'Hide','我的空间':'My space','起始页':'Home','我的书架':'Library','收藏站点':'Bookmarks','忙里有闲，':'Take a break,','阅读有屿。':'find a story.','把片刻时间，还给自己。':'Make a moment your own.','偏好设置':'Preferences','本地运行':'Stored locally','▧ 小窗':'▧ Compact','▧ 展开':'▧ Expand','♧ 置顶':'♧ Pin','☷ 阅读设置':'☷ Settings','◌ 一键隐藏':'◌ Hide',
'轻一点，读一会儿':'Slow down. Read a little','轻一点，读一会儿。':'Slow down. Read a little.','一本书，一个网页，一小段属于自己的时间。':'A book, a page, a moment just for you.','✧ 让阅读，轻轻发生':'✧ Make room for reading','在日常的缝隙里，':'Between the busy moments,','发现另一片海。':'find another world.','打开喜欢的网站，或接着读完昨天的故事。':'Open a favorite site or pick up yesterday’s story.','调低透明度，让内容融入你的桌面。':'Let your reading blend into your desktop.','＋ 导入一本书':'＋ Import a book','体验阅读 →':'Try reading →','常去的地方':'Favorite places','＋ 添加站点':'＋ Add a site','前往 ↗':'Go ↗','继续阅读':'Continue reading','＋ 导入书籍':'＋ Import books','支持 TXT / EPUB / PDF':'TXT / EPUB / PDF supported','书籍与阅读记录仅保存在本机':'Books and progress stay on this device','给自己一点留白。':'Make room for yourself.','随时开始，随时收起':'Open when you like. Hide when you need.',
'☰ 目录':'☰ Contents','← 上一章':'← Previous','下一章 →':'Next →','阅读进度 0%':'Progress 0%','滚动阅读 · 进度自动保存':'Scroll to read · Progress saved automatically','阅读设置':'Reading settings','调成你最舒服的样子。':'Make it comfortable.','▤ Word 贴合：只留正文':'▤ Text-only overlay','鼠标移到窗口上沿即可显示拖动把手和设置按钮；移开自动收起。右键也可打开设置。':'Hover near the top edge for Drag and Settings. Move away to hide the toolbar. Right-click also opens settings.',
'透明模式':'Transparent mode','收起工具栏后仅保留正文':'Hide the controls to show text only','窗口不透明度':'Window opacity','轻盈':'Subtle','清晰':'Clear','鼠标移出隐藏':'Hide when pointer leaves','移回原位置即可恢复':'Move back to the same area to restore','始终置顶':'Always on top','让窗口停留在最前面':'Keep this window above other apps','字号 / 网页缩放':'Font size / Page zoom','阅读文字颜色':'Text color','隐藏网页图片':'Hide page images','同时隐藏视频与画布':'Also hides video and canvas','自动滚动':'Auto-scroll','关闭':'Off','显示 / 隐藏窗口':'Show / hide window','完全退出':'Quit application','保存快捷键':'Save shortcuts','例如 Alt+Z、Ctrl+Shift+Q。关闭窗口后，可从系统托盘恢复。':'For example Alt+Z or Ctrl+Shift+Q. Restore a hidden window from the system tray.','↻ 恢复默认阅读设置':'↻ Reset reading settings',
'收藏一处好地方':'Save a favorite place','下次想来，一点就到。':'Just one click away next time.','站点名称':'Site name','网址':'URL','取消':'Cancel','添加收藏':'Add bookmark','网站地址':'Website address','输入网址，去你想去的地方':'Enter a website address','当前网址':'Current address','例如：我的博客':'For example: My blog','显示隐藏快捷键':'Show/hide shortcut','退出快捷键':'Quit shortcut','按住这里拖动窗口':'Hold to drag the window','显示完整工具栏':'Show all controls','隐藏整个窗口':'Hide the whole window','收起悬浮工具栏':'Collapse floating toolbar','最小化':'Minimize','最大化 / 还原':'Maximize / Restore','隐藏到托盘':'Hide to tray','切换小窗阅读':'Toggle compact window','窗口始终置顶':'Always on top','后退':'Back','前进':'Forward','刷新':'Reload','收藏当前网站':'Bookmark this page','返回起始页':'Back to home',
'还没有收藏。点击「添加站点」，收藏你的第一个网站。':'No bookmarks yet. Choose Add a site to save one.','移除收藏':'Remove bookmark','轻屿原创 · 示例读物':'Original sample · Office Escape','上班摸鱼神器原创 · 示例读物':'Original sample · Office Escape','未开始':'Not started','继续阅读 →':'Continue →','从本地书架移除':'Remove from library','已移除书架副本，原文件保留':'Removed from the library. The original file is unchanged.','把下一段故事放进来':'Make room for another story','导入本地书籍':'Import local books','每一本，都是一座岛。':'Every book is a little escape.','常去的地方，随时抵达。':'Your favorite places, one click away.','我的空间 / 起始页':'My space / Home','我的空间 / 我的书架':'My space / Library','我的空间 / 收藏站点':'My space / Bookmarks','把喜欢的故事收在这里，下一次接着读。':'Keep your stories here and pick up where you left off.','收藏值得停留的网站，为自己留一扇窗。':'Save sites worth spending a little time with.','轻浏览 / 网页':'Browse / Web','我的书架 / 阅读':'Library / Reading','书籍已加入本地书架':'Book added to the local library','站点已收藏':'Site bookmarked','已收藏当前网站':'Page bookmarked','本地 PDF':'Local PDF','PDF 使用内置阅读器；字号、滚动与进度以 PDF 工具栏为准':'PDF uses the built-in viewer. Use its toolbar for zoom and navigation.',
'显示 / 收起阅读工具栏（Alt+R）':'Toggle reading controls (Alt+R)','关闭透明模式':'Turn off transparency','隐藏窗口':'Hide window','退出':'Quit','显示轻屿':'Show Office Escape','显示上班摸鱼神器':'Show Office Escape','阅读工具栏（Alt+R）':'Reading controls (Alt+R)','恢复不透明窗口':'Restore an opaque window','导入本地书籍':'Import local books','电子书':'Books','Alt+R 用于唤回阅读工具栏，请选择其他快捷键':'Alt+R is reserved for reading controls. Choose another shortcut.','快捷键已被占用或格式不正确':'This shortcut is unavailable or invalid.','文件超过 50 MB，请拆分后导入':'This file exceeds 50 MB. Split it before importing.','暂不支持此格式':'This file format is not supported.','书籍不存在':'Book not found.','无权访问':'Access denied.','未知操作':'Unknown action.','请输入有效的 http 或 https 网址':'Enter a valid HTTP or HTTPS URL.',
'微信读书':'WeRead','哔哩哔哩':'Bilibili','抖音':'Douyin','粉笔':'Fenbi','让阅读成为习惯':'Make reading a habit','发现有趣的世界':'Explore something new','记录美好生活':'A little everyday inspiration','每天进步一点点':'Learn a little every day',
'给生活留一点空白':'A Little Room for Yourself','随笔':'Essay'
};
function translate(text,lang){if(lang!=='en')return text;if(en[text])return en[text];let m;
if((m=text.match(/^阅读进度 (\d+)%$/)))return `Progress ${m[1]}%`;
if((m=text.match(/^已读 (\d+)%$/)))return `${m[1]}% read`;
if((m=text.match(/^(.+) · 本地书籍$/)))return `${m[1]} · Local book`;
if((m=text.match(/^页面加载失败：(.*)$/)))return `Page failed to load: ${m[1]}`;
return text;}
if(typeof module==='object'&&module.exports){module.exports={translate};return;}
let language=localStorage.getItem('office-escape-language')||'zh-CN';
const original=new WeakMap(),attributes=new WeakMap();
const excluded='#chapter-text,#chapter-title,#reader-book-name,#toc,.book-cover span,.book-meta h4,[data-no-i18n],script,style,textarea,option';
function apply(){
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;
 while((n=walker.nextNode())){if(n.parentElement?.closest(excluded))continue;const cached=original.get(n);const source=cached&&n.data===cached.rendered?cached.source:n.data;const trimmed=source.trim();if(!trimmed)continue;const value=source.replace(trimmed,translate(trimmed,language));original.set(n,{source,rendered:value});if(n.data!==value)n.data=value;}
 for(const node of document.querySelectorAll('[title],[placeholder],[aria-label]')){let record=attributes.get(node)||{};for(const key of ['title','placeholder','aria-label']){const current=node.getAttribute(key);if(current===null)continue;const old=record[key];const source=old&&current===old.rendered?old.source:current;const value=translate(source,language);record[key]={source,rendered:value};if(value!==current)node.setAttribute(key,value);}attributes.set(node,record);}
 document.documentElement.lang=language;document.title=translate('上班摸鱼神器 · 透明阅读工具',language);const select=document.getElementById('language');if(select)select.value=language;
}
let scheduled=false;
const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;observer.disconnect();apply();observe();});});
function observe(){observer.observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['title','placeholder','aria-label']});}
function setLanguage(lang,persist=true){const previous=language;language=lang==='en'?'en':'zh-CN';localStorage.setItem('office-escape-language',language);observer.disconnect();apply();observe();if(previous!==language)window.dispatchEvent(new CustomEvent('language-changed'));if(persist&&window.qingyu)window.qingyu.call('settings',{language}).catch(()=>{});}
window.i18n={translate:text=>translate(text,language),setLanguage,get language(){return language;}};
apply();observe();document.getElementById('language').addEventListener('change',e=>setLanguage(e.target.value));
})();
