const $=id=>document.getElementById(id);
const api=window.qingyu;let settings={},library=[],sites=[],page='home',activeBook=null,chapters=[],chapter=0,toastTimer,saveTimer,restoring=false;
let controlsVisible=true, mousePeek=false, dragActive=false, peekTimer;
function setMousePeek(value){clearTimeout(peekTimer);mousePeek=value;document.body.classList.toggle('mouse-peek',value);requestAnimationFrame(updateBounds);}
function closeMousePeekSoon(){clearTimeout(peekTimer);if(!dragActive)peekTimer=setTimeout(()=>setMousePeek(false),400);}

function syncImmersive(){const reading=!$('content-page').hidden;const immersive=!!settings.transparent&&reading&&!controlsVisible;document.body.classList.toggle('immersive',immersive);if(!immersive)setMousePeek(false);requestAnimationFrame(updateBounds);}
function toggleControls(){controlsVisible=!controlsVisible;syncImmersive();}
const defaults=[{title:'微信读书',url:'https://weread.qq.com',icon:'▥',tag:'让阅读成为习惯'},{title:'哔哩哔哩',url:'https://www.bilibili.com',icon:'▣',tag:'发现有趣的世界'},{title:'抖音',url:'https://www.douyin.com',icon:'♪',tag:'记录美好生活'},{title:'粉笔',url:'https://www.fenbi.com',icon:'✎',tag:'每天进步一点点'}];
const demo={id:'demo',title:'给生活留一点空白',format:'随笔',progress:0,chapter:0,scroll:0};
const demoChapters=[{title:'第一章  慢下来，也没关系',text:'清晨的第一束光，落在窗边的书页上。\n\n城市还没有完全醒来。远处有一辆公交车经过，声音像潮水，缓缓地来，又缓缓地退去。\n\n你给自己泡了一杯茶，没有急着打开消息。那些需要回复的邮件、等待处理的表格，就让它们再等一小会儿。此刻，这五分钟只属于你。\n\n我们总习惯把生活填满。日历上的每一个空格都应该有所安排，每一段路程都应该有所收获。直到某一天，我们发现，自己已经很久没有认真看过窗外的一棵树。\n\n它每天都在那里。风来的时候，叶子翻出浅绿的背面，像一本正在被轻轻翻动的书。\n\n读书也是这样。你不必一定读到某一页，不必记住每一句话。你只是坐下来，进入另一种节奏，让别人的故事把你带到远一点的地方。\n\n远到可以暂时忘记时钟，却又近到随时能够回来。\n\n也许你读到一条安静的小路，一间亮着灯的厨房，或者一个正在等雨停的人。那些普通的片刻，在文字里慢慢变得清晰。\n\n你忽然意识到，生活并不总需要宏大的意义。把茶喝完，把这一页读完，把呼吸放慢一点，已经很好。\n\n窗外的光向前挪了一点。你合上书，回到自己的事情里。世界没有因此改变，但你心里多出了一点空间。\n\n那是你为自己留下的小岛。\n\n忙碌会继续，故事也是。下一次休息的时候，再回到这里。'},{title:'第二章  一座随身的小岛',text:'不一定要走很远，才能找到安静。\n\n一段文字、一首歌、一杯慢慢变凉的茶，都可以成为日常里的小岛。\n\n你来到这里，放下肩上的东西。没有待办清单，没有必须完成的目标。只有一阵风，和正在展开的一页。\n\n在上班摸鱼神器，你可以导入自己的 TXT、EPUB 或 PDF，也可以打开常去的网站。阅读进度会留在这台电脑上，等你下一次回来。\n\n试着打开右上角的阅读设置，选一个舒服的字号。或者把透明度调低一点，让文字轻轻浮在桌面上。\n\n愿你在每一个忙碌的日子里，都能拥有一点属于自己的时间。'}];
function toast(msg){$('toast').textContent=String(msg).replace(/^Error invoking remote method 'qingyu': Error: /,'');$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200);}
async function call(action,payload){try{return await api.call(action,payload);}catch(e){toast(e.message);return undefined;}}
function el(tag,cls,text){const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;}
function renderSites(){const grid=$('site-grid');grid.replaceChildren();const items=page==='sites'?sites:[...defaults,...sites];if(!items.length){grid.append(el('p','format-note','还没有收藏。点击「添加站点」，收藏你的第一个网站。'));return;}
 for(const site of items){const wrap=el('div','site-wrap'),btn=el('button','site-card');btn.append(el('span','site-icon',site.icon||'◎'));const detail=el('div');if(sites.includes(site))detail.dataset.noI18n='';detail.append(el('b','',site.title),el('small','',site.tag||new URL(site.url).hostname));btn.append(detail,el('span','','↗'));btn.onclick=()=>openWeb(site.url);wrap.append(btn);if(sites.includes(site)){const remove=el('button','remove-site','×');remove.title='移除收藏';remove.onclick=async()=>{sites=await call('removeSite',site.url)||sites;renderSites();};wrap.append(remove);}grid.append(wrap);}}
function renderBooks(){const grid=$('book-grid');grid.replaceChildren();$('book-count').textContent=library.length;const books=page==='library'?library:[...library.slice(0,3)];if(!books.length)books.push(demo);
 for(const book of books){const card=el('div','book-card');card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label','阅读 '+book.title);const cover=el('div','book-cover');cover.append(el('span','',book.title.slice(0,12)),el('small','',book.id==='demo'?'OFFICE ESCAPE':book.format));const meta=el('div','book-meta');meta.append(el('h4','',book.title),el('small','',book.id==='demo'?'上班摸鱼神器原创 · 示例读物':book.format+' · 本地书籍'));const track=el('div','progress-track'),fill=el('div');fill.style.width=(book.progress||0)+'%';track.append(fill);const progress=el('div','book-progress');progress.append(el('span','',book.progress?'已读 '+Math.round(book.progress)+'%':'未开始'),el('span','','继续阅读 →'));meta.append(track,progress);card.append(cover,meta);card.onclick=()=>openBook(book.id);card.onkeydown=e=>{if(e.key==='Enter')openBook(book.id);};if(book.id!=='demo'){const del=el('button','delete-book','×');del.title='从本地书架移除';del.onclick=async e=>{e.stopPropagation();library=await call('remove',book.id)||library;renderBooks();toast('已移除书架副本，原文件保留');};card.append(del);}grid.append(card);}
 const add=el('button','empty-book');add.append(el('span','','＋'));const text=el('div');text.append(el('b','','把下一段故事放进来'),el('small','','导入本地书籍'));add.append(text);add.onclick=importBook;grid.append(add);}
async function showPage(next){await saveProgress();await call('home');page=next;activeBook=null;$('dashboard').hidden=false;$('content-page').hidden=true;document.querySelectorAll('[data-page]').forEach(n=>n.classList.toggle('active',n.dataset.page===next));const title={home:'轻一点，读一会儿。',library:'每一本，都是一座岛。',sites:'常去的地方，随时抵达。'};$('page-title').textContent=title[next];$('breadcrumb').textContent='我的空间 / '+({home:'起始页',library:'我的书架',sites:'收藏站点'}[next]);$('page-description').textContent=next==='library'?'把喜欢的故事收在这里，下一次接着读。':next==='sites'?'收藏值得停留的网站，为自己留一扇窗。':'一本书，一个网页，一小段属于自己的时间。';$('hero').hidden=next!=='home';$('web-section').hidden=next==='library';$('library-section').hidden=next==='sites';renderSites();renderBooks();syncImmersive();}
function contentMode(web){controlsVisible=!settings.transparent;$('dashboard').hidden=true;$('content-page').hidden=false;$('web-host').hidden=!web;$('reader').hidden=web;for(const id of ['back','forward','reload','bookmark'])$(id).disabled=!web;$('current-url').readOnly=!web;syncImmersive();}
async function openWeb(url){await saveProgress();activeBook=null;contentMode(true);$('current-url').value=url;$('breadcrumb').textContent='轻浏览 / 网页';await updateBounds();await call('web',url);}
async function openBook(id){await saveProgress();const data=id==='demo'?{book:demo,chapters:window.i18n.language==='en'?englishDemo:demoChapters}:await call('book',id);if(!data)return;if(id==='demo')await call('home');activeBook=data.book;chapters=data.chapters||[];chapter=Math.min(activeBook.chapter||0,Math.max(0,chapters.length-1));contentMode(!chapters.length);$('current-url').value=activeBook.title;$('breadcrumb').textContent='我的书架 / 阅读';if(chapters.length){$('reader-book-name').textContent=activeBook.title;renderChapter(activeBook.scroll||0);}else toast('PDF 使用内置阅读器；字号、滚动与进度以 PDF 工具栏为准');}
function renderChapter(scroll=0){restoring=true;$('chapter-title').textContent=chapters[chapter].title;$('chapter-text').textContent=chapters[chapter].text;$('chapter-count').textContent=`${chapter+1} / ${chapters.length}`;$('prev-chapter').disabled=chapter===0;$('next-chapter').disabled=chapter===chapters.length-1;$('toc').replaceChildren();chapters.forEach((c,i)=>{const btn=el('button','',c.title);btn.onclick=()=>{saveProgress();chapter=i;renderChapter();$('toc').hidden=true;};$('toc').append(btn);});requestAnimationFrame(()=>{$('reading-scroll').scrollTop=scroll;restoring=false;progressLabel();});}
function getProgress(){const a=$('reading-scroll'),ratio=a.scrollHeight>a.clientHeight?a.scrollTop/(a.scrollHeight-a.clientHeight):1;return ((chapter+ratio)/chapters.length)*100;}
function progressLabel(){if(activeBook&&chapters.length)$('read-progress').textContent='阅读进度 '+Math.round(getProgress())+'%';}
async function saveProgress(){clearTimeout(saveTimer);if(!activeBook||!chapters.length||restoring)return;const p={id:activeBook.id,chapter,scroll:$('reading-scroll').scrollTop,progress:getProgress()};Object.assign(activeBook,p);if(p.id!=='demo'){Object.assign(library.find(b=>b.id===p.id)||{},p);await call('progress',p);}}
async function importBook(){const result=await call('import');if(result){library=result;renderBooks();toast('书籍已加入本地书架');}}
function applySettings(){window.i18n.setLanguage(settings.language||'zh-CN',false);document.body.classList.toggle('transparent',settings.transparent);document.documentElement.style.setProperty('--read-size',settings.fontSize+'px');document.documentElement.style.setProperty('--read-color',settings.textColor);for(const key of ['transparent','hideOnLeave','top','hideImages'])$(key).checked=settings[key];for(const key of ['opacity','fontSize','autoScroll'])$(key).value=key==='opacity'?Math.round(settings.opacity*100):settings[key];$('opacity-value').textContent=Math.round(settings.opacity*100)+'%';$('fontSize-value').textContent=settings.fontSize;$('autoScroll-value').textContent=settings.autoScroll?settings.autoScroll+' px/s':'关闭';$('textColor').value=settings.textColor;$('bossKey').value=settings.bossKey;$('quitKey').value=settings.quitKey;$('boss-label').textContent=settings.bossKey.replaceAll('+',' ');$('pin').classList.toggle('selected',settings.top);syncImmersive();}
async function changeSettings(p){const result=await call('settings',p);if(result){settings=result;applySettings();}}
function toggleSettings(force){controlsVisible=true;$('settings').hidden=typeof force==='boolean'?!force:!$('settings').hidden;if($('settings').hidden&&settings.transparent)controlsVisible=false;syncImmersive();}
async function updateBounds(){if($('web-host').hidden||$('content-page').hidden)return;const r=$('web-host').getBoundingClientRect();const inset=document.body.classList.contains('immersive')?(mousePeek?52:28):0;await call('bounds',{x:r.x,y:r.y+inset,width:r.width,height:Math.max(0,r.height-inset)});}
for(const key of ['transparent','hideOnLeave','top','hideImages'])$(key).onchange=e=>changeSettings({[key]:e.target.checked});for(const key of ['opacity','fontSize','autoScroll'])$(key).oninput=e=>changeSettings({[key]:Number(e.target.value)/(key==='opacity'?100:1)});$('textColor').oninput=e=>changeSettings({textColor:e.target.value});
$('save-keys').onclick=()=>changeSettings({bossKey:$('bossKey').value.trim(),quitKey:$('quitKey').value.trim()});$('reset-settings').onclick=()=>changeSettings({opacity:1,transparent:false,hideOnLeave:false,hideImages:false,top:false,fontSize:18,textColor:'#39483f',autoScroll:0});
$('word-preset').onclick=async()=>{
 if($('content-page').hidden)await openBook('demo');
 await changeSettings({transparent:true,opacity:1,textColor:'#333333',fontSize:16,top:true});
 document.body.classList.add('compact');$('compact').textContent='▧ 展开';
 await call('compact','strip');toggleSettings(false);controlsVisible=false;syncImmersive();
};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&settings.transparent&&!$('content-page').hidden&&!$('site-dialog').open){e.preventDefault();toggleControls();}});
document.addEventListener('contextmenu',e=>{if(settings.transparent){e.preventDefault();call('reading-menu');}});
$('compact').onclick=async()=>{const enabled=!document.body.classList.contains('compact');document.body.classList.toggle('compact',enabled);$('compact').textContent=enabled?'▧ 展开':'▧ 小窗';toggleSettings(false);await call('compact',enabled);requestAnimationFrame(updateBounds);};
$('pin').onclick=()=>changeSettings({top:!settings.top});$('settings-nav').onclick=$('settings-button').onclick=()=>toggleSettings();$('close-settings').onclick=()=>toggleSettings(false);
$('minimize').onclick=()=>call('window','minimize');$('maximize').onclick=()=>call('window','maximize');$('close').onclick=$('boss').onclick=()=>{saveProgress();call('window','hide');};
$('hero-import').onclick=$('import-book').onclick=importBook;$('try-reading').onclick=()=>openBook('demo');document.querySelectorAll('[data-page]').forEach(n=>n.onclick=()=>showPage(n.dataset.page));
$('address-form').onsubmit=e=>{e.preventDefault();if($('address').value.trim())openWeb($('address').value);};$('current-url').onkeydown=e=>{if(e.key==='Enter'&&!e.target.readOnly)openWeb(e.target.value);};$('return-home').onclick=()=>showPage('home');for(const n of ['back','forward','reload'])$(n).onclick=()=>call('navigate',n);
$('add-site').onclick=()=>{$('site-dialog').showModal();};$('cancel-site').onclick=()=>$('site-dialog').close();$('site-form').onsubmit=async e=>{e.preventDefault();const result=await call('site',{title:$('site-name').value,url:$('site-url').value});if(result){sites=result;renderSites();$('site-dialog').close();$('site-form').reset();toast('站点已收藏');}};
$('bookmark').onclick=async()=>{const result=await call('site',{url:$('current-url').value});if(result){sites=result;toast('已收藏当前网站');}};
$('toc-toggle').onclick=()=>$('toc').hidden=!$('toc').hidden;for(const [id,delta] of [['prev-chapter',-1],['next-chapter',1]])$(id).onclick=async()=>{await saveProgress();chapter+=delta;renderChapter();};$('reading-scroll').onscroll=()=>{progressLabel();clearTimeout(saveTimer);saveTimer=setTimeout(saveProgress,350);};
new ResizeObserver(updateBounds).observe($('content-area'));$('date').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'short'});
api.onState(data=>{if(data.toggleControls)toggleControls();if(data.showSettings)toggleSettings(true);if(data.error)toast(data.error);if(data.settings){settings=data.settings;applySettings();}if(data.url)$('current-url').value=data.url;if(data.loading!==undefined)$('reload').textContent=data.loading?'⋯':'↻';if(data.scrollBy&&!$('reader').hidden)$('reading-scroll').scrollBy(0,data.scrollBy);});
(async()=>{const init=await call('init');if(!init)return;({settings,library,sites}=init);applySettings();localizeSample();renderSites();renderBooks();})();

// Mouse-only controls: transparent until the pointer reaches the upper edge.
$('mouse-zone').addEventListener('pointerenter',()=>setMousePeek(true));
$('mouse-zone').addEventListener('pointerleave',closeMousePeekSoon);
$('mouse-settings').onclick=()=>toggleSettings(true);
$('mouse-expand').onclick=()=>{controlsVisible=true;syncImmersive();};
$('mouse-hide').onclick=()=>{setMousePeek(false);saveProgress();call('window','hide');};
$('mouse-dismiss').onclick=()=>setMousePeek(false);
$('mouse-drag').addEventListener('pointerdown',e=>{
 if(e.button!==0)return;e.preventDefault();dragActive=true;clearTimeout(peekTimer);
 e.currentTarget.setPointerCapture(e.pointerId);call('drag-start',{x:e.screenX,y:e.screenY});
});
$('mouse-drag').addEventListener('pointermove',e=>{if(dragActive)call('drag-move',{x:e.screenX,y:e.screenY});});
function endMouseDrag(){if(!dragActive)return;dragActive=false;call('drag-end');closeMousePeekSoon();}
$('mouse-drag').addEventListener('pointerup',endMouseDrag);
$('mouse-drag').addEventListener('pointercancel',endMouseDrag);
$('mouse-drag').addEventListener('lostpointercapture',endMouseDrag);
window.addEventListener('blur',()=>{endMouseDrag();setMousePeek(false);});

const englishDemo=[{title:'Chapter 1 · A little room for yourself',text:'The first light of the morning rests on an open page.\n\nThe city is still waking up. A bus passes somewhere outside, its sound arriving and fading like a small wave.\n\nYou make a cup of tea. For a moment, the messages and spreadsheets can wait. These few minutes belong to you.\n\nWe are used to filling every space in our day. Every journey needs a purpose; every empty square on a calendar seems to ask for a plan. But sometimes a quiet pause is enough.\n\nReading offers another rhythm. You do not have to finish a chapter or remember every sentence. You can simply sit down and let a story take you somewhere else.\n\nPerhaps there is a quiet street, a kitchen with a light on, or someone waiting for the rain to stop. Small, ordinary moments become clear again.\n\nFinish your tea. Read another page. Take a breath. You can return to your work with a little more space in your mind.\n\nThe world will keep moving. Your story will be here when you return.'},{title:'Chapter 2 · Your portable island',text:'You do not have to travel far to find a quiet place.\n\nA few lines of a story, a song, or a slowly cooling cup of tea can become a small island in your day.\n\nOffice Escape keeps your books and reading progress on this device. Import a TXT, EPUB, or PDF file, or visit a favorite website.\n\nTry the text-only overlay in Reading settings. Hover near the top edge to reveal the mouse controls. Hold Drag to move the window; choose Settings to adjust it. Move away and the toolbar disappears.\n\nThere is no rush. Leave a little room for yourself.'}];
function localizeSample(){$('date').textContent=new Date().toLocaleDateString(window.i18n.language==='en'?'en-US':'zh-CN',{month:'short',day:'numeric',weekday:'short'});demo.title=window.i18n.language==='en'?'A Little Room for Yourself':'给生活留一点空白';if(activeBook?.id==='demo'){chapters=window.i18n.language==='en'?englishDemo:demoChapters;$('reader-book-name').textContent=demo.title;renderChapter($('reading-scroll').scrollTop);}renderBooks();}
window.addEventListener('language-changed',localizeSample);
